version: '3.7'

services:

  movie_api:
    image: movie_api
    depends_on:
      - "db"
    container_name: movie_api
    ports:
      - "5000:80"
    build: 
      context: .
      dockerfile: dockerfile
    networks:
      - dev

  db:
    image: postgres:latest
    container_name: movieapi_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

networks:
  dev:
    driver: bridge 
    
volumes:
  customer_data:
  pgadmin: